### ISSUE TITLE
Axon service fails to start due to scapy import error

### ISSUE THREAD

**Issue by skourtes** [vmware/validation-app-engine#14]
After installation, the service fails to start due to:

root@20-20-11-1:~# systemctl status axon
● axon.service - Axon Traffic Generation Service Daemon
   Loaded: loaded (/etc/systemd/system/axon.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Tue 2020-09-15 16:51:38 UTC; 15min ago
  Process: 15554 ExecStart=/usr/bin/python3 -maxon.controller.axon_rpyc_controller (code=exited, status=1/FAILURE)
 Main PID: 15554 (code=exited, status=1/FAILURE)

Sep 15 16:51:38 20-20-11-1 python3[15554]:     "__main__", mod_spec)
Sep 15 16:51:38 20-20-11-1 python3[15554]:   File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
Sep 15 16:51:38 20-20-11-1 python3[15554]:     exec(code, run_globals)
Sep 15 16:51:38 20-20-11-1 python3[15554]:   File "/opt/axon/controller/axon_rpyc_controller.py", line 20, in <module>
Sep 15 16:51:38 20-20-11-1 python3[15554]:     from axon.apps.scapy import Scapy
Sep 15 16:51:38 20-20-11-1 python3[15554]:   File "/opt/axon/apps/scapy.py", line 11, in <module>
Sep 15 16:51:38 20-20-11-1 python3[15554]:     from scapy.all import *
Sep 15 16:51:38 20-20-11-1 python3[15554]: ModuleNotFoundError: No module named 'scapy'
Sep 15 16:51:38 20-20-11-1 systemd[1]: axon.service: Main process exited, code=exited, status=1/FAILURE
Sep 15 16:51:38 20-20-11-1 systemd[1]: axon.service: Failed with result 'exit-code'.

**Comment by skourtes** [comment]
Submitted too soon. I checked the requirements.txt and it does include scapy 2.4.3. Workaround to get the service to start is to comment out the following line in axon/apps/scapy.py:

from scapy.all import *

Currently on exec function is used from this module and now it revert to using the built-in instead.

**Comment by gitvipin** [comment]
Yea we need to do install python dependencies , as of now in this release, at endpoints separately.
